import { useCallback } from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { useLEDWizard } from '@/hooks/useLEDWizard';
import { Header } from '@/components/Header';
import { Toolbar } from '@/components/Toolbar';
import { ControlPanel } from '@/components/ControlPanel';
import { LEDCanvas } from '@/components/LEDCanvas';
import { StatsPanel } from '@/components/StatsPanel';
import { toast } from 'sonner';

const Index = () => {
  const {
    settings,
    updateSettings,
    canvasState,
    setCanvasState,
    handleZoom,
    handlePan,
    resetCanvas,
    letterData,
    stats,
    clearText,
  } = useLEDWizard();

  const handleExportPDF = useCallback(async () => {
    const canvas = document.getElementById('led-canvas-container');
    if (!canvas) return;

    try {
      toast.info('Generating PDF...');
      
      // Get the actual canvas element for accurate export
      const canvasElement = await html2canvas(canvas, {
        backgroundColor: '#ffffff',
        scale: 3, // Higher resolution for accurate export
        useCORS: true,
      });
      
      const imgData = canvasElement.toDataURL('image/png');
      
      // Calculate proper aspect ratio for the PDF
      const canvasWidth = canvasElement.width;
      const canvasHeight = canvasElement.height;
      const aspectRatio = canvasWidth / canvasHeight;
      
      // Create PDF with proper orientation based on content
      const isLandscape = aspectRatio > 1;
      const pdf = new jsPDF({
        orientation: isLandscape ? 'landscape' : 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      // Header
      pdf.setFontSize(20);
      pdf.setTextColor(31, 41, 55);
      pdf.text('Illuminate — Layout Specification', 15, 18);

      // Project info
      pdf.setFontSize(9);
      pdf.setTextColor(107, 114, 128);
      const infoY = 28;
      pdf.text(`Text: ${settings.text}`, 15, infoY);
      pdf.text(`Font: ${settings.fontFamily}`, 15, infoY + 5);
      pdf.text(`Dimensions: ${stats.totalWidth}mm × ${stats.totalHeight}mm (H: ${settings.letterHeight}mm, D: ${settings.letterDepth}mm)`, 15, infoY + 10);
      pdf.text(`Module: ${settings.moduleType.name} | Total Modules: ${stats.totalModules}`, 15, infoY + 15);
      pdf.text(`Power: ${stats.totalPower}W | PSU: ${stats.powerSupplyCount}× ${settings.powerSupply.name} (${stats.powerSupplyLoad}% load)`, 15, infoY + 20);

      // Calculate image placement - maintain aspect ratio accurately
      const maxImgWidth = pageWidth - 30;
      const maxImgHeight = pageHeight - 85;
      
      let imgWidth = maxImgWidth;
      let imgHeight = imgWidth / aspectRatio;
      
      if (imgHeight > maxImgHeight) {
        imgHeight = maxImgHeight;
        imgWidth = imgHeight * aspectRatio;
      }
      
      const imgX = (pageWidth - imgWidth) / 2;
      const imgY = 55;
      
      // Add border around image
      pdf.setDrawColor(229, 231, 235);
      pdf.setLineWidth(0.5);
      pdf.rect(imgX - 1, imgY - 1, imgWidth + 2, imgHeight + 2);
      
      pdf.addImage(imgData, 'PNG', imgX, imgY, imgWidth, imgHeight);

      // Letter breakdown at bottom
      const breakdownY = imgY + imgHeight + 10;
      if (breakdownY < pageHeight - 20) {
        pdf.setFontSize(8);
        pdf.setTextColor(107, 114, 128);
        const nonSpaceLetters = letterData.filter(l => l.char !== ' ');
        const breakdown = nonSpaceLetters.map(l => `${l.char}: ${l.moduleCount}`).join(' | ');
        pdf.text(`Letter Modules: ${breakdown}`, 15, breakdownY);
      }

      // Footer
      pdf.setFontSize(7);
      pdf.setTextColor(156, 163, 175);
      pdf.text(`Generated by Illuminate — ${new Date().toLocaleDateString()}`, 15, pageHeight - 8);

      pdf.save(`illuminate-${settings.text.toLowerCase().replace(/\s+/g, '-')}.pdf`);
      toast.success('PDF exported successfully!');
    } catch (error) {
      console.error('PDF export error:', error);
      toast.error('Failed to export PDF');
    }
  }, [settings, stats, letterData]);

  const handleExportImage = useCallback(async () => {
    const canvas = document.getElementById('led-canvas-container');
    if (!canvas) return;

    try {
      toast.info('Generating image...');
      
      const canvasElement = await html2canvas(canvas, {
        backgroundColor: '#ffffff',
        scale: 3, // High resolution
        useCORS: true,
      });
      
      const link = document.createElement('a');
      link.download = `illuminate-${settings.text.toLowerCase().replace(/\s+/g, '-')}.png`;
      link.href = canvasElement.toDataURL('image/png');
      link.click();
      
      toast.success('Image exported successfully!');
    } catch (error) {
      console.error('Image export error:', error);
      toast.error('Failed to export image');
    }
  }, [settings.text]);

  const handleClear = useCallback(() => {
    clearText();
    toast.success('Diagram cleared');
  }, [clearText]);

  return (
    <div className="min-h-screen bg-background flex flex-col font-inter">
      <Header />

      <main className="flex-1 container mx-auto px-4 py-4">
        {/* Toolbar */}
        <Toolbar
          onExportPDF={handleExportPDF}
          onExportImage={handleExportImage}
          onClear={handleClear}
          onResetCanvas={resetCanvas}
          onZoomIn={() => handleZoom(0.2)}
          onZoomOut={() => handleZoom(-0.2)}
        />

        {/* Main layout */}
        <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr_280px] gap-4 mt-4 min-h-[calc(100vh-180px)]">
          {/* Left panel - Controls */}
          <div className="hidden lg:block">
            <ControlPanel settings={settings} onUpdateSettings={updateSettings} />
          </div>

          {/* Center - Canvas */}
          <LEDCanvas
            letterData={letterData}
            settings={settings}
            canvasState={canvasState}
            setCanvasState={setCanvasState}
            onZoom={handleZoom}
            onPan={handlePan}
          />

          {/* Right panel - Stats */}
          <div className="hidden lg:block">
            <StatsPanel stats={stats} settings={settings} letterData={letterData} />
          </div>
        </div>

        {/* Mobile panels */}
        <div className="lg:hidden mt-4 space-y-4">
          <ControlPanel settings={settings} onUpdateSettings={updateSettings} />
          <StatsPanel stats={stats} settings={settings} letterData={letterData} />
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-3 text-center text-xs text-muted-foreground font-inter bg-card">
        Illuminate © {new Date().getFullYear()} — Professional LED Layout Tool
      </footer>
    </div>
  );
};

export default Index;
